# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shop-dashboard"
client_id = ""
application_url = "https://compensation-land-barbados-kissing.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://compensation-land-barbados-kissing.trycloudflare.com/auth/callback",
  "https://compensation-land-barbados-kissing.trycloudflare.com/auth/shopify/callback",
  "https://compensation-land-barbados-kissing.trycloudflare.com/api/auth/callback",
  "https://compensation-land-barbados-kissing.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "al-janat-demo.myshopify.com"
